### ISSUE TITLE
Reading logged data from code?

### ISSUE THREAD

**Issue by HyperDuino** [microbit-foundation/DAPLink#13]
Is there any way to read logged data from the MakeCode program? What I want to be able to do is restore a variable after a reset or battery failure.

**Comment by microbit-carlos** [comment]
DAPLink v255 (the version released with micro:bit V2) provides the functionality to write and read storage data via I2C.

CODAL offers two ways to use the DAPLink storage, read and write raw data is available using the lower level `uBit.flash`, or the `uBit.log` data logging can be used to write tabular data (the data is then exposed via the MY_DATA.HTM file in the MICROBIT drive).

MakeCode and MicroPython only expose the CODAL data logging API, but a MakeCode C++ extension could be used to read and write raw data in the DAPLink storage using `uBit.flash`.

Apart from that, this recent PR merged into CODAL (not yet released to MakeCode) adds data logging read capabilities from the CODAL side: https://github.com/lancaster-university/codal-microbit-v2/pull/177
