### ISSUE TITLE
ChromeOS update breaks WebUSB

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/DAPLink#14]
We've got some reports:
- https://twitter.com/stulowe80/status/1570618991064010753
- https://support.microbit.org/a/tickets/56726
- https://support.microbit.org/a/tickets/56839
- https://support.microbit.org/a/tickets/56866
- https://support.microbit.org/a/tickets/56900

And @microbit-giles has been able to replicate in his Chromebook at version v105, and @martinwork with the beta channel at v106.

In macOs I have been unable to replicate with Chrome 105 or Chrome Canary at 107.

We think this issue could have been introduced in v105, but cannot spot anything on the release notes:
- https://developer.chrome.com/blog/new-in-chrome-105/
- https://developer.chrome.com/blog/deps-rems-105/
- https://chromereleases.googleblog.com/2022/08/stable-channel-update-for-desktop_30.html
- https://chromereleases.googleblog.com/2022/09/stable-channel-update-for-chromeos.html

**Comment by microbit-carlos** [comment]
Already reported in the Chrome bug tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1363712&q=usb&can=2

And a patch is under review: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/3897018/1

**Comment by martinwork** [comment]
In my tests on 106 beta, the WebUSB connection did not work at all, while some of the support tickets report problems like 105 being able to flash, but having to reconnect the USB cable and the WebUSB each time.

**Comment by microbit-carlos** [comment]
Looks like this will be fixed in v106 to be released on September 29:
https://chromiumdash.appspot.com/schedule

**Comment by microbit-carlos** [comment]
I'll close this as this was resolved in ChromeOS with the v106 release from last month.
