### ISSUE TITLE
speed doesn't improve at all 

### ISSUE THREAD

**Issue by nathansuperuser** [microbit-foundation/DAPLink#18]

**Comment by microbit-carlos** [comment]
Hi @NathanGithub2013, thank you for your feedback. Could you provide a bit more info? What have you tried and what how long did it take before and after upgrading DAPLink?

**Comment by nathansuperuser** [comment]
I had measure the time to download my file before and after the update and
it's 39 sec before and 36 sec after


Vào 15:54, Th 3, 11 thg 4, 2023 Carlos Pereira Atencio <
***@***.***> đã viết:

**Comment by microbit-carlos** [comment]
Thanks for the additional info @NathanGithub2013!

Wow, 39 seconds is quite long. Could you provide a bit more info about your test computer?
What kind of flashing did you perform? Was it copy and pasting a hex file into the `MICROBIT` drive? Or using the online editors with WebUSB?
Could you post the hex file here? (email attachments won't work, you'd have to add it to a comment directly from the GitHub website). It might be better if the file is first compressed into a zip file or similar.
What kind of computer specs do you have? Operating system version, etc.
Do you run any antivirus software of similar that could be interacting with the flashing?

**Comment by nathansuperuser** [comment]
Web usb



Vào 18:10, Th 3, 11 thg 4, 2023 Carlos Pereira Atencio <
***@***.***> đã viết:

**Comment by nathansuperuser** [comment]
MBP 2011 MacOS 10.15

Vào 21:24, Th 3, 11 thg 4, 2023 Ralph Nathan ***@***.***>
đã viết:

**Comment by nathansuperuser** [comment]
No antivirus


Vào 21:25, Th 3, 11 thg 4, 2023 Ralph Nathan ***@***.***>
đã viết:

**Comment by microbit-carlos** [comment]
Thanks Nathan!
Right, in the case of using WebUSB we usually find that CPU speed can be important factor, and in the case of older computers it can be the bottleneck. That's probably why the DAPLink updates have only resulted in an ~7% speed improvement. This is a known limitation and there isn't much we can do at the moment to improve performance.

Thank you for your feedback and for providing the additional information!

**Comment by nathansuperuser** [comment]
Thanks for the feedback!

Vào 21:34, Th 3, 11 thg 4, 2023 Carlos Pereira Atencio <
***@***.***> đã viết:
