### ISSUE TITLE
WebUSB name configuration

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/DAPLink#2]
For the new WebUSB feature the USB device appears as `DAPLink CMSIS-DAP`.
We need to look into how general board configurations are designed, how WebUSB configurations will be done, and what do we need for the micro:bit board.

Ideally we'd want the `BBC micro:bit` string to appear in the USB device name instead of `DAPLink CMSIS-DAP`.

It would be even better if we could have have the "friendly" name used for BLE that generates a different name based on nRF51 UUID (`BBC micro:bit [xxxxx]`), but might be difficult to achieve, depending on the configuration being defined in a yml file or C code.

**Comment by jaustin** [comment]
size: s

**Comment by jaustin** [comment]
Needs discussion with the mbed/DAPlink team

**Comment by microbit-carlos** [comment]
Currently the version of WebUSB in master has `DAPLink CMSIS-DAP` as the board name for all boards.

There is a bug where on first connection it shows `LPC1768`, this is likely is a bug outside of DAPLink caused by having this VID and PID associated with that board and windows not getting the correct value from the descriptor on first load.

**Comment by microbit-carlos** [comment]
micro:bit name in Chrome is now `BBC micro:bit CMSIS-DAP`.
Implemented in https://github.com/ARMmbed/DAPLink/pull/488.
