### ISSUE TITLE
Comparison issues

### ISSUE THREAD

**Issue by MarianSavchuk** [microbit-foundation/DAPLink#9]
@gerargz, 
I just noticed that these two comparisons are always false.
https://github.com/microbit-foundation/DAPLink/blob/44a2522d35038eb51f04b363a6bb4ff437e46467/source/daplink/interface/swd_host.c#L1070
https://github.com/microbit-foundation/DAPLink/blob/44a2522d35038eb51f04b363a6bb4ff437e46467/source/daplink/interface/swd_host.c#L1081
Is this how it should be or is it a typo?

**Comment by microbit-carlos** [comment]
Thanks for the report @MarianSavchuk, and great catch!
This has been addressed upstream in PR  https://github.com/ARMmbed/DAPLink/pull/853, which has been already merged there 🎉
